[workspace]
members = [
    "corelib",
    "demo",
    "executable",
    "shared"
]

resolver = "3"


# 公共依赖
[workspace.dependencies]
tokio = { version = "1.48.0", features = ["full"] }
slint = "1.12.1"
uniffi = "0.30.0"