// This file is generated by rust-protobuf 3.7.2. Do not edit
// .proto file is parsed by protoc --rs_out=...
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `multi2.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_2;

// @@protoc_insertion_point(message:mypackage.AddressBook)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct AddressBook {
    // message fields
    // @@protoc_insertion_point(field:mypackage.AddressBook.bookname)
    pub bookname: ::std::string::String,
    // @@protoc_insertion_point(field:mypackage.AddressBook.people)
    pub people: ::std::vec::Vec<super::multi1::Person>,
    // special fields
    // @@protoc_insertion_point(special_field:mypackage.AddressBook.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a AddressBook {
    fn default() -> &'a AddressBook {
        <AddressBook as ::protobuf::Message>::default_instance()
    }
}

impl AddressBook {
    pub fn new() -> AddressBook {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "bookname",
            |m: &AddressBook| { &m.bookname },
            |m: &mut AddressBook| { &mut m.bookname },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "people",
            |m: &AddressBook| { &m.people },
            |m: &mut AddressBook| { &mut m.people },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<AddressBook>(
            "AddressBook",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for AddressBook {
    const NAME: &'static str = "AddressBook";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.bookname = is.read_string()?;
                },
                18 => {
                    self.people.push(is.read_message()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.bookname.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.bookname);
        }
        for value in &self.people {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.bookname.is_empty() {
            os.write_string(1, &self.bookname)?;
        }
        for v in &self.people {
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> AddressBook {
        AddressBook::new()
    }

    fn clear(&mut self) {
        self.bookname.clear();
        self.people.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static AddressBook {
        static instance: AddressBook = AddressBook {
            bookname: ::std::string::String::new(),
            people: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for AddressBook {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("AddressBook").unwrap()).clone()
    }
}

impl ::std::fmt::Display for AddressBook {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for AddressBook {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x0cmulti2.proto\x12\tmypackage\x1a\x0cmulti1.proto\"T\n\x0bAddressBoo\
    k\x12\x1a\n\x08bookname\x18\x01\x20\x01(\tR\x08bookname\x12)\n\x06people\
    \x18\x02\x20\x03(\x0b2\x11.mypackage.PersonR\x06peopleJ\xd1\x01\n\x06\
    \x12\x04\0\0\n\x01\n\x08\n\x01\x0c\x12\x03\0\0\x12\n\x08\n\x01\x02\x12\
    \x03\x02\0\x12\n\x1f\n\x02\x03\0\x12\x03\x05\0\x16\x1a\x14\x20\xe5\xaf\
    \xbc\xe5\x85\xa5\xe5\xbc\x95\xe7\x94\xa8\x20proto\n\n\n\n\x02\x04\0\x12\
    \x04\x07\0\n\x01\n\n\n\x03\x04\0\x01\x12\x03\x07\x08\x13\n\x0b\n\x04\x04\
    \0\x02\0\x12\x03\x08\x02\x16\n\x0c\n\x05\x04\0\x02\0\x05\x12\x03\x08\x02\
    \x08\n\x0c\n\x05\x04\0\x02\0\x01\x12\x03\x08\t\x11\n\x0c\n\x05\x04\0\x02\
    \0\x03\x12\x03\x08\x14\x15\n\x0b\n\x04\x04\0\x02\x01\x12\x03\t\x02\x1d\n\
    \x0c\n\x05\x04\0\x02\x01\x04\x12\x03\t\x02\n\n\x0c\n\x05\x04\0\x02\x01\
    \x06\x12\x03\t\x0b\x11\n\x0c\n\x05\x04\0\x02\x01\x01\x12\x03\t\x12\x18\n\
    \x0c\n\x05\x04\0\x02\x01\x03\x12\x03\t\x1b\x1cb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(1);
            deps.push(super::multi1::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(AddressBook::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
